id: I63D5BD96
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:34:08.960974'
last_modified: '2022-06-19T09:34:08.960986'
parser: null
source_metadata:
  title: Hagiography of Zhwa lu mkhan chen Rin chen bsod nams mchog grub (1602–1681);
    Lamdre Lobshe, vol. ca, title no. 1
  author: ངག་དབང་བློ་བཟང་བརྒྱ་མཚོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-04);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/573
  bases:
    9bdc:
      title: Hagiography of Zhwa lu mkhan chen Rin chen bsod nams mchog grub (1602–1681);
        Lamdre Lobshe, vol. ca, title no. 1
      order: 1
      base_file: 9bdc.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
